version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - gosec
    - ineffassign
    - unused
    - revive
    - misspell
    - unconvert
    - copyloopvar

  settings:
    gosec:
      excludes:
        - G104

    revive:
      rules:
        - name: exported
          severity: warning
        - name: error-return
        - name: error-naming
        - name: if-return
        - name: var-naming

  exclusions:
    generated: lax
    rules:
      # Skip all enabled linters for these generated files
      - path: _bpfel\.go$
        linters:
          - lll

      - path: _bpfeb\.go$
        linters:
          - lll

      - source: "^//go:generate "
        linters:
          - lll

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
