// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type WgReverseProxyMetricsKey struct {
	_       structs.HostLayout
	Dir     uint8
	Reason  uint8
	Pad     uint16
	SrcAddr uint32
}

type WgReverseProxyMetricsValue struct {
	_       structs.HostLayout
	Packets uint64
	Bytes   uint64
}

type WgReverseProxyXorKey struct {
	_   structs.HostLayout
	Key [32]uint8
}

// LoadWgReverseProxy returns the embedded CollectionSpec for WgReverseProxy.
func LoadWgReverseProxy() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_WgReverseProxyBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load WgReverseProxy: %w", err)
	}

	return spec, err
}

// LoadWgReverseProxyObjects loads WgReverseProxy and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*WgReverseProxyObjects
//	*WgReverseProxyPrograms
//	*WgReverseProxyMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadWgReverseProxyObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadWgReverseProxy()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// WgReverseProxySpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type WgReverseProxySpecs struct {
	WgReverseProxyProgramSpecs
	WgReverseProxyMapSpecs
	WgReverseProxyVariableSpecs
}

// WgReverseProxyProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type WgReverseProxyProgramSpecs struct {
	WgReverseProxy *ebpf.ProgramSpec `ebpf:"wg_reverse_proxy"`
}

// WgReverseProxyMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type WgReverseProxyMapSpecs struct {
	MetricsMap *ebpf.MapSpec `ebpf:"metrics_map"`
}

// WgReverseProxyVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type WgReverseProxyVariableSpecs struct {
	CfgPaddingEnabled  *ebpf.VariableSpec `ebpf:"__cfg_padding_enabled"`
	CfgPaddingFillMode *ebpf.VariableSpec `ebpf:"__cfg_padding_fill_mode"`
	CfgPaddingMax      *ebpf.VariableSpec `ebpf:"__cfg_padding_max"`
	CfgPaddingMin      *ebpf.VariableSpec `ebpf:"__cfg_padding_min"`
	CfgWgPort          *ebpf.VariableSpec `ebpf:"__cfg_wg_port"`
	CfgXorEnabled      *ebpf.VariableSpec `ebpf:"__cfg_xor_enabled"`
	CfgXorKey          *ebpf.VariableSpec `ebpf:"__cfg_xor_key"`
	CfgXorKeyLen       *ebpf.VariableSpec `ebpf:"__cfg_xor_key_len"`
}

// WgReverseProxyObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadWgReverseProxyObjects or ebpf.CollectionSpec.LoadAndAssign.
type WgReverseProxyObjects struct {
	WgReverseProxyPrograms
	WgReverseProxyMaps
	WgReverseProxyVariables
}

func (o *WgReverseProxyObjects) Close() error {
	return _WgReverseProxyClose(
		&o.WgReverseProxyPrograms,
		&o.WgReverseProxyMaps,
	)
}

// WgReverseProxyMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadWgReverseProxyObjects or ebpf.CollectionSpec.LoadAndAssign.
type WgReverseProxyMaps struct {
	MetricsMap *ebpf.Map `ebpf:"metrics_map"`
}

func (m *WgReverseProxyMaps) Close() error {
	return _WgReverseProxyClose(
		m.MetricsMap,
	)
}

// WgReverseProxyVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadWgReverseProxyObjects or ebpf.CollectionSpec.LoadAndAssign.
type WgReverseProxyVariables struct {
	CfgPaddingEnabled  *ebpf.Variable `ebpf:"__cfg_padding_enabled"`
	CfgPaddingFillMode *ebpf.Variable `ebpf:"__cfg_padding_fill_mode"`
	CfgPaddingMax      *ebpf.Variable `ebpf:"__cfg_padding_max"`
	CfgPaddingMin      *ebpf.Variable `ebpf:"__cfg_padding_min"`
	CfgWgPort          *ebpf.Variable `ebpf:"__cfg_wg_port"`
	CfgXorEnabled      *ebpf.Variable `ebpf:"__cfg_xor_enabled"`
	CfgXorKey          *ebpf.Variable `ebpf:"__cfg_xor_key"`
	CfgXorKeyLen       *ebpf.Variable `ebpf:"__cfg_xor_key_len"`
}

// WgReverseProxyPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadWgReverseProxyObjects or ebpf.CollectionSpec.LoadAndAssign.
type WgReverseProxyPrograms struct {
	WgReverseProxy *ebpf.Program `ebpf:"wg_reverse_proxy"`
}

func (p *WgReverseProxyPrograms) Close() error {
	return _WgReverseProxyClose(
		p.WgReverseProxy,
	)
}

func _WgReverseProxyClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed wgreverseproxy_bpfeb.o
var _WgReverseProxyBytes []byte
